# ── Terminal ───────────────────────────────────────────────
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ag terminal-overrides ",xterm-256color:UTF-8"
set -as terminal-features "xterm-256color:usstyle"

# ── Clipboard ─────────────────────────────────────────────
set -g set-clipboard on
set -g allow-passthrough on
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "clipcopy"

# ── Mouse ─────────────────────────────────────────────────
set -g mouse on
